/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uam.calc.gui;

import java.util.regex.Pattern;
import javax.swing.ButtonModel;
import uam.calc.Calculadora;
import uam.model.Binario;
import uam.model.CA1;
import uam.model.CA2;
import uam.model.Convertible;
import uam.model.Decimal;
import uam.model.Hexadecimal;
import uam.model.Numero;
import uam.model.Octal;

/**
 *
 * @author santi
 */
public class Vista extends javax.swing.JFrame 
{
    private final Calculadora calculadora;
    
    private final String DECIMAL = "decimal";
    private final String HEXADECIMAL = "hexadecimal";
    private final String BINARIO = "binario";
    private final String OCTAL = "octal";

    /**
     * Creates new form Vista
     * @param calculadora
     */
    public Vista(Calculadora calculadora) 
    {
        initComponents();
        this.calculadora = calculadora;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txInp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaResult = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        lbSisN = new javax.swing.JLabel();
        btnD = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnEq = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnMB = new javax.swing.JButton();
        btnGr = new javax.swing.JButton();
        btnCA1 = new javax.swing.JButton();
        btnCA2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        txInp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txaResult.setEditable(false);
        txaResult.setBackground(new java.awt.Color(204, 204, 204));
        txaResult.setColumns(20);
        txaResult.setRows(5);
        jScrollPane1.setViewportView(txaResult);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Decimal");
        jRadioButton1.setActionCommand("decimal");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Binario");
        jRadioButton2.setActionCommand("binario");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Octal");
        jRadioButton3.setActionCommand("octal");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Hexadecimal");
        jRadioButton4.setActionCommand("hexadecimal");

        lbSisN.setFont(new java.awt.Font("FreeMono", 1, 12)); // NOI18N
        lbSisN.setForeground(new java.awt.Color(102, 102, 102));
        lbSisN.setText("...");

        btnD.setText("D");
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });

        btnA.setText("A");
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });

        btnB.setText("B");
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnF.setText("F");
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });

        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnP.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnP.setText("+");
        btnP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });

        btnM.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnM.setText("-");
        btnM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });

        btnEq.setBackground(new java.awt.Color(51, 51, 51));
        btnEq.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEq.setForeground(new java.awt.Color(255, 255, 255));
        btnEq.setText("=");
        btnEq.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqActionPerformed(evt);
            }
        });

        btnDiv.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDiv.setText("/");
        btnDiv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnMB.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMB.setText("*");
        btnMB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMBActionPerformed(evt);
            }
        });

        btnGr.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGr.setText("GRAY");
        btnGr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrActionPerformed(evt);
            }
        });

        btnCA1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCA1.setText("CA1");
        btnCA1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCA1ActionPerformed(evt);
            }
        });

        btnCA2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCA2.setText("CA2");
        btnCA2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCA2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txInp)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbSisN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2)
                                        .addGap(48, 48, 48)
                                        .addComponent(jRadioButton3)
                                        .addGap(39, 39, 39)
                                        .addComponent(jRadioButton4)
                                        .addGap(53, 53, 53)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCA1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCA2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEq, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txInp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSisN, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnF, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMB, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCA1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEq, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCA2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String buildStr(String str,int caretPos, String c)
    {
        String left = str.substring(0, caretPos);
        String right = str.substring(caretPos);  
        return left + c + right;
    }
    
    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
       
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "A"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "B"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
       
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "C"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "D"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "E"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "F"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnFActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "+"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnPActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
       
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "-"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnMActionPerformed

    private void btnMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMBActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "*"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnMBActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        
        int caretPos = txInp.getCaretPosition();
        txInp.setText(buildStr(txInp.getText(), caretPos, "/"));
        txInp.setCaretPosition(caretPos+1);
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqActionPerformed
        
        String in = txInp.getText();
        if(validateBinOpRegex(in)&in.contains("+"))
        {
            Numero num1 = new Binario(in.substring(0, in.indexOf("+")));
            Numero num2 = new Binario(in.substring(in.indexOf("+")+1));
            Numero sum = calculadora.sum(num1, num2);
            System.out.println("Sum: "+sum.getNum());
            txaResult.setText(txaResult.getText()+"\n"+txInp.getText()+"\n");
            txaResult.setText(txaResult.getText()+"\n"+"sum: "+sum.getNum()+"\n");
            txInp.setText(sum.getNum()); 
            return;
        }
        Decimal toDecimal;
        Binario toBinario;
        Octal toOctal;
        Hexadecimal toHexadecimal;
        
        ButtonModel selection = buttonGroup1.getSelection();
        System.out.println(selection.getActionCommand());
        switch(selection.getActionCommand())
        {
            case "decimal":
                if(!validateDecRegex(in))
                {
                    lbSisN.setText("Expresión malformada");
                    return;
                }                
                Decimal decimal = new Decimal(in);                
                toBinario = calculadora.toBinary(decimal);                
                toHexadecimal = calculadora.toHexadecimal(decimal);
                toOctal = calculadora.toOctal(decimal);                
                lbSisN.setText(toBinario.toString());
                lbSisN.setText(lbSisN.getText()+"; ");
                lbSisN.setText(lbSisN.getText()+toHexadecimal.toString());
                lbSisN.setText(lbSisN.getText()+"; ");
                lbSisN.setText(lbSisN.getText()+toOctal.toString());
                break;
            case "binario":
                if(!validateBinRegex(in))
                {
                    lbSisN.setText("Expresión malformada");
                    return;
                }
                Binario bin = new Binario(in);
                toDecimal = calculadora.toDecimal(bin);
                toHexadecimal = calculadora.toHexadecimal(bin);
                toOctal = calculadora.toOctal(bin);
                lbSisN.setText("Decimal: "+toDecimal.getNum());
                lbSisN.setText(lbSisN.getText()+"; Hexadecimal: "+toHexadecimal.getNum());
                lbSisN.setText(lbSisN.getText()+"; Octal: "+toOctal.getNum()); 
                break;  
            case "octal":
                if(!validateOctRegex(in))
                {
                    lbSisN.setText("Expresión malformada");
                    return;
                }
                Octal oct = new Octal(in);
                toDecimal = calculadora.toDecimal(oct);
                toBinario = calculadora.toBinary(oct);
                toHexadecimal = calculadora.toHexadecimal(oct);
                lbSisN.setText("Decimal: "+toDecimal.getNum());
                lbSisN.setText(lbSisN.getText()+"; Binario: "+toBinario.getNum());
                lbSisN.setText(lbSisN.getText()+"; Hexadecimal: "+toHexadecimal.getNum());
                break;
            case "hexadecimal":
                if(!validateHexRegex(in))
                {
                    lbSisN.setText("Expresión malformada");
                    return;
                }
                Hexadecimal hex = new Hexadecimal(in);
                toDecimal = calculadora.toDecimal(hex);
                toBinario = calculadora.toBinary(hex);
                toOctal = calculadora.toOctal(hex);
                lbSisN.setText("Decimal: "+toDecimal.getNum());
                lbSisN.setText(lbSisN.getText()+"; Binario: "+toBinario.getNum());
                lbSisN.setText(lbSisN.getText()+"; Octal: "+toOctal.getNum());
                break;
        }
        
        // if bin sel
                   
        
    }//GEN-LAST:event_btnEqActionPerformed

    private void btnCA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCA1ActionPerformed
       
        Convertible num = getIn();
        CA1 toCA1 = calculadora.toCA1(num);
        txaResult.setText(txaResult.getText()+"\n"+txInp.getText()+"\n");
        txaResult.setText(txaResult.getText()+"\n"+"CA1 "+toCA1.getNum()+"\n");
        txInp.setText(toCA1.getNum());                
    }//GEN-LAST:event_btnCA1ActionPerformed

    private void btnCA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCA2ActionPerformed
        Convertible num = getIn();
        CA2 toCA2 = calculadora.toCA2(num);
        txaResult.setText(txaResult.getText()+"\n"+txInp.getText()+"\n");
        txaResult.setText(txaResult.getText()+"\n"+"CA2 "+toCA2.getNum()+"\n");
        txInp.setText(toCA2.getNum());  
    }//GEN-LAST:event_btnCA2ActionPerformed

    private void btnGrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrActionPerformed
    
    private Convertible getIn()
    {
        String in = txInp.getText();
        String selection = buttonGroup1.getSelection().getActionCommand();
        switch(selection)
        {
            case DECIMAL:
                return new Decimal(in);
            case BINARIO:
                return new Binario(in);
            case OCTAL:
                return new Octal(in);
            case HEXADECIMAL:
                return new Hexadecimal(in);
        }
        throw new UnsupportedOperationException();
    }
    
    private boolean validateBinOpRegex(String exp) 
    {
        return Pattern.matches("([01]+)(((\\+?)([01]+)+)*)", exp);
    }
    
    private boolean validateBinRegex(String exp) 
    {
        return Pattern.matches("([01]+)", exp);
    }
    
    private boolean validateDecRegex(String exp) 
    {
        return Pattern.matches("([0-9]+)", exp);
    }
    
    private boolean validateOctRegex(String exp) 
    {
        return Pattern.matches("([0-7]+)", exp);
    }
    
    private boolean validateHexRegex(String exp) 
    {
        return Pattern.matches("([A-F0-9]+)", exp);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCA1;
    private javax.swing.JButton btnCA2;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEq;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnGr;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnMB;
    private javax.swing.JButton btnP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSisN;
    private javax.swing.JTextField txInp;
    private javax.swing.JTextArea txaResult;
    // End of variables declaration//GEN-END:variables
}
